services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --reload --port 8007
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://localhost:27017
      - JWT_SECRET=supersecretkeychange
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRE_MIN=60
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8007
    command: sh -c "npm run dev"

volumes:
  mongo-data:
